### DISCUSSION TITLE
✅ Working Apple Silicon / macOS workaround for ComfyUI FP8 MPS

### DISCUSSION THREAD

**Discussion by vSnake87** [Comfy-Org/ComfyUI#13273] [General]
Working Apple Silicon / macOS workaround for ComfyUI FP8 MPS crash after updates

I’m sharing a working local workaround for Apple Silicon users running ComfyUI on macOS with the MPS backend and hitting this error:

TypeError: Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

In my case, the issue returned after a ComfyUI update because the files I had previously patched were overwritten again.

What fixed it for me was patching two separate locations:

1. ComfyUI core
   /Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/float.py

2. comfy_kitchen inside the local ComfyUI virtual environment
   ~/ComfyUI/.venv/lib/python3.12/site-packages/comfy_kitchen/backends/eager/quantization.py

Why both patches were necessary in my setup:
- one failure path happened in ComfyUI core inside `stochastic_rounding(...)`
- another failure path happened inside `comfy_kitchen` in `dequantize_per_tensor_fp8(...)`

The logic of the workaround is simple:
- if the tensor is on MPS
- move the FP8-related operation to CPU
- perform the conversion or dequantization there
- move the resulting tensor back to the original device if needed

After patching both files, the official LTX 2.3 workflow worked again correctly on my Apple Silicon Mac with MPS enabled.

More importantly, in my case this was not limited to a single workflow. After applying both patches, all FP8 models I personally tested in ComfyUI were able to launch and run without triggering the Float8_e4m3fn MPS backend crash. I cannot guarantee identical results for every environment, but on my machine this consistently resolved the FP8-on-MPS failure path.

Because updates can overwrite the modified files again, I wrapped the workaround into a small Python patcher script so I can re-apply it quickly after future ComfyUI updates.

Important notes:
- this is not an official upstream fix
- this is a local workaround
- it assumes the ComfyUI Desktop app path on macOS
- it also assumes a local ComfyUI venv layout similar to `~/ComfyUI/.venv/...`
- users should review and adjust paths if their installation layout is different

Sanitized patcher script:

```python
from pathlib import Path
from datetime import datetime
import py_compile
import shutil
import sys

HOME = Path.home()

FLOAT_PATH = Path("/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/float.py")
KITCHEN_PATH = HOME / "ComfyUI/.venv/lib/python3.12/site-packages/comfy_kitchen/backends/eager/quantization.py"

STAMP = datetime.now().strftime("%Y%m%d_%H%M%S")


def backup_file(path: Path):
    backup = path.with_name(path.name + f".bak_{STAMP}")
    shutil.copy2(path, backup)
    print(f"[backup] {path} -> {backup}")


def patch_float_py():
    path = FLOAT_PATH
    text = path.read_text()

    if 'on_mps = value.device.type == "mps"' in text:
        print("[ok] float.py already appears patched")
        return False

    start = text.find("def stochastic_rounding(value, dtype, seed=0):")
    end = text.find("\n# TODO: improve this?", start)

    if start == -1 or end == -1:
        raise RuntimeError("Could not find stochastic_rounding() boundaries in float.py")

    new_block = '''def stochastic_rounding(value, dtype, seed=0):
    if dtype == torch.float32:
        return value.to(dtype=torch.float32)
    if dtype == torch.float16:
        return value.to(dtype=torch.float16)
    if dtype == torch.bfloat16:
        return value.to(dtype=torch.bfloat16)
    if dtype == torch.float8_e4m3fn or dtype == torch.float8_e5m2:
        on_mps = value.device.type == "mps"
        if on_mps:
            value = value.cpu()

        generator = torch.Generator(device=value.device)
        generator.manual_seed(seed)
        output = torch.empty_like(value, dtype=dtype)
        num_slices = max(1, (value.numel() / (4096 * 4096)))
        slice_size = max(1, round(value.shape[0] / num_slices))

        for i in range(0, value.shape[0], slice_size):
            output[i:i+slice_size].copy_(
                manual_stochastic_round_to_float8(
                    value[i:i+slice_size], dtype, generator=generator
                )
            )

        return output

    return value.to(dtype=dtype)

'''

    backup_file(path)
    patched = text[:start] + new_block + text[end + 1 :]
    path.write_text(patched)
    py_compile.compile(str(path), doraise=True)
    print("[patched] float.py")
    return True


def patch_quantization_py():
    path = KITCHEN_PATH
    text = path.read_text()

    if 'target_device = x.device' in text and 'if x.device.type == "mps":' in text:
        print("[ok] quantization.py already appears patched")
        return False

    old = """def dequantize_per_tensor_fp8(
    x: torch.Tensor, scale: torch.Tensor, output_type: torch.dtype = torch.bfloat16
) -> torch.Tensor:
    dq_tensor = x.to(dtype=output_type) * scale.to(dtype=output_type)
    return dq_tensor
"""

    new = """def dequantize_per_tensor_fp8(
    x: torch.Tensor, scale: torch.Tensor, output_type: torch.dtype = torch.bfloat16
) -> torch.Tensor:
    target_device = x.device

    if x.device.type == "mps":
        x = x.cpu()
        scale = scale.cpu()

    dq_tensor = x.to(dtype=output_type) * scale.to(dtype=output_type)

    if target_device.type == "mps":
        dq_tensor = dq_tensor.to(target_device)

    return dq_tensor
"""

    if old not in text:
        raise RuntimeError("Could not find the original dequantize_per_tensor_fp8() block in quantization.py")

    backup_file(path)
    text = text.replace(old, new, 1)
    path.write_text(text)
    py_compile.compile(str(path), doraise=True)
    print("[patched] quantization.py")
    return True


def verify():
    float_text = FLOAT_PATH.read_text()
    kitchen_text = KITCHEN_PATH.read_text()

    float_ok = 'on_mps = value.device.type == "mps"' in float_text
    kitchen_ok = 'target_device = x.device' in kitchen_text and 'if x.device.type == "mps":' in kitchen_text

    print(f"[verify] float.py: {'OK' if float_ok else 'MISSING PATCH'}")
    print(f"[verify] quantization.py: {'OK' if kitchen_ok else 'MISSING PATCH'}")

    return float_ok and kitchen_ok


def main():
    try:
        patch_float_py()
        patch_quantization_py()
        ok = verify()

        if ok:
            print("\nDone. You can launch ComfyUI.")
        else:
            print("\nPatch was not fully applied.")
            sys.exit(2)

    except Exception as e:
        print(f"\n[ERROR] {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
```
How to use:

Save the script as something like patch_comfy_mps_fp8.py
Close ComfyUI
Run the script with Python
Re-open ComfyUI
Re-run your FP8 workflow

If anyone else on Apple Silicon tests this successfully on additional FP8 models or workflows, it would be useful to compare results.
[patch_comfy_mps_fp8.py](https://github.com/user-attachments/files/26470837/patch_comfy_mps_fp8.py)

**Comment by tedd4u** [comment]
I happened to run across a pull request to fix this issue (that's not merged yet).
https://github.com/Comfy-Org/ComfyUI/pull/12378

**Comment by michaellpankau** [comment]
This did not fix it for me on a fresh installation. Same error as before - identical to yours.

**Reply by vSnake87** [reply]
Can you confirm that both patch locations were actually modified on your machine?

In my case, patching only one file was not enough. I had to patch both:
1. ComfyUI core: `comfy/float.py`
2. comfy_kitchen: `.../site-packages/comfy_kitchen/backends/eager/quantization.py`

Also, please check whether your installation paths match the ones assumed by the script. If your ComfyUI app path or local venv path is different, the patch may not have been applied even though the script ran.

If possible, please share:
- your exact traceback
- the output of the patcher script
- the actual paths used by your ComfyUI installation

**Reply by ernest-cook** [reply]
I tried this and it didn't work initially but I discovered the desktop app version had a little different directory for the quantization bit, after updating the script with the new path it worked great.  Thank you for putting this together @vSnake87

**Reply by michaellpankau** [reply]
Patch appears to have worked fine but I'm still getting an error:


Script log:
Python 3.14.5 (v3.14.5:5607950ef23, May 10 2026, 07:38:09) [Clang 21.0.0 (clang-2100.0.123.102)] on darwin
Enter "help" below or click "Help" above for more information.

=========== RESTART: /Users/USERNAME/Downloads/patch_comfy_mps_fp8.py ===========
[ok] float.py already appears patched
[ok] quantization.py already appears patched
[verify] float.py: OK
[verify] quantization.py: OK

Done. You can launch ComfyUI.



Here is the job run log:

TypeError: Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.



# ComfyUI Error Report
## Error Details
- **Node ID:** 433:3
- **Node Type:** KSampler
- **Exception Type:** TypeError
- **Exception Message:** TypeError: Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

## Stack Trace
```
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 535, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 335, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 309, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 297, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 1578, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 1542, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/sample.py", line 74, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1180, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1070, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1052, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 995, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 981, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 751, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/k_diffusion/sampling.py", line 205, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 400, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 954, in __call__
    return self.outer_predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 961, in outer_predict_noise
    ).execute(x, timestep, model_options, seed)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 964, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 380, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 205, in calc_cond_batch
    return _calc_cond_batch_outer(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 213, in _calc_cond_batch_outer
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 325, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_base.py", line 182, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_base.py", line 226, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/qwen_image/model.py", line 427, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/qwen_image/model.py", line 499, in _forward
    hidden_states = self.img_in(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 482, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 474, in forward_comfy_cast_weights
    weight, bias, offload_stream = cast_bias_weight(self, input, offloadable=True)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 352, in cast_bias_weight
    bias = bias.to(dtype=bias_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** 0.22.2
- **Arguments:** /Applications/ComfyUI.app/Contents/Resources/ComfyUI/main.py --user-directory /Users/mpankau/ComfyUI/user --input-directory /Users/mpankau/ComfyUI/input --output-directory /Users/mpankau/ComfyUI/output --front-end-root /Applications/ComfyUI.app/Contents/Resources/ComfyUI/web_custom_versions/desktop_app --base-directory /Users/mpankau/ComfyUI --database-url sqlite:////Users/mpankau/ComfyUI/user/comfyui.db --extra-model-paths-config /Users/mpankau/Library/Application Support/ComfyUI/extra_models_config.yaml --log-stdout --listen 127.0.0.1 --port 8000 --enable-manager
- **OS:** darwin
- **Python Version:** 3.12.11 (main, Aug 18 2025, 19:02:39) [Clang 20.1.4 ]
- **Embedded Python:** false
- **PyTorch Version:** 2.12.0
## Devices

- **Name:** mps
  - **Type:** mps
  - **VRAM Total:** 25769803776
  - **VRAM Free:** 7374815232
  - **Torch VRAM Total:** 25769803776
  - **Torch VRAM Free:** 7374815232

## Logs
```
2026-05-27T09:58:43.313480 - setup plugin alembic.autogenerate.schemas
2026-05-27T09:58:43.313537 - setup plugin alembic.autogenerate.tables
2026-05-27T09:58:43.313559 - setup plugin alembic.autogenerate.types
2026-05-27T09:58:43.313576 - setup plugin alembic.autogenerate.constraints
2026-05-27T09:58:43.313591 - setup plugin alembic.autogenerate.defaults
2026-05-27T09:58:43.313604 - setup plugin alembic.autogenerate.comments
2026-05-27T09:58:43.367014 - Could not autodetect AIMDO implementation, assuming Nvidia
2026-05-27T09:58:43.367126 - comfy-aimdo unsupported operating system: Darwin
2026-05-27T09:58:43.367139 - NOTE: comfy-aimdo currently only supports Windows and Linux
2026-05-27T09:58:43.445631 - Adding extra search path custom_nodes /Users/mpankau/ComfyUI/custom_nodes
2026-05-27T09:58:43.445674 - Adding extra search path download_model_base /Users/mpankau/ComfyUI/models
2026-05-27T09:58:43.445690 - Adding extra search path custom_nodes /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes
2026-05-27T09:58:43.445703 - Setting output directory to: /Users/mpankau/ComfyUI/output
2026-05-27T09:58:43.445718 - Setting input directory to: /Users/mpankau/ComfyUI/input
2026-05-27T09:58:43.445734 - Setting user directory to: /Users/mpankau/ComfyUI/user
2026-05-27T09:58:43.579926 - [START] Security scan2026-05-27T09:58:43.579939 - 
2026-05-27T09:58:43.625608 - [ComfyUI-Manager] Using uv as Python module for pip operations.
2026-05-27T09:58:43.710345 - [DONE] Security scan2026-05-27T09:58:43.710376 - 
2026-05-27T09:58:43.711193 - ** ComfyUI startup time:2026-05-27T09:58:43.711221 -  2026-05-27T09:58:43.711237 - 2026-05-27 09:58:43.7112026-05-27T09:58:43.711249 - 
2026-05-27T09:58:43.711267 - ** Platform:2026-05-27T09:58:43.711277 -  2026-05-27T09:58:43.711287 - Darwin2026-05-27T09:58:43.711297 - 
2026-05-27T09:58:43.711305 - ** Python version:2026-05-27T09:58:43.711313 -  2026-05-27T09:58:43.711320 - 3.12.11 (main, Aug 18 2025, 19:02:39) [Clang 20.1.4 ]2026-05-27T09:58:43.711328 - 
2026-05-27T09:58:43.711335 - ** Python executable:2026-05-27T09:58:43.711342 -  2026-05-27T09:58:43.711349 - /Users/mpankau/ComfyUI/.venv/bin/python2026-05-27T09:58:43.711356 - 
2026-05-27T09:58:43.711364 - ** ComfyUI Path:2026-05-27T09:58:43.711371 -  2026-05-27T09:58:43.711378 - /Applications/ComfyUI.app/Contents/Resources/ComfyUI2026-05-27T09:58:43.711384 - 
2026-05-27T09:58:43.711391 - ** ComfyUI Base Folder Path:2026-05-27T09:58:43.711399 -  2026-05-27T09:58:43.711406 - /Applications/ComfyUI.app/Contents/Resources/ComfyUI2026-05-27T09:58:43.711414 - 
2026-05-27T09:58:43.711441 - ** User directory:2026-05-27T09:58:43.711447 -  2026-05-27T09:58:43.711454 - /Users/mpankau/ComfyUI/user2026-05-27T09:58:43.711461 - 
2026-05-27T09:58:43.711468 - ** ComfyUI-Manager config path:2026-05-27T09:58:43.711474 -  2026-05-27T09:58:43.711480 - /Users/mpankau/ComfyUI/user/__manager/config.ini2026-05-27T09:58:43.711486 - 
2026-05-27T09:58:43.711495 - ** Log path:2026-05-27T09:58:43.711565 -  2026-05-27T09:58:43.711572 - /Users/mpankau/ComfyUI/user/comfyui.log2026-05-27T09:58:43.711578 - 
2026-05-27T09:58:43.772199 - [ComfyUI-Manager] Skipped fixing the 'comfyui-frontend-package' dependency because the ComfyUI is outdated.
2026-05-27T09:58:43.772445 - [PRE] ComfyUI-Manager
2026-05-27T09:58:44.984239 - Found comfy_kitchen backend triton: {'available': False, 'disabled': True, 'unavailable_reason': "ImportError: No module named 'triton'", 'capabilities': []}
2026-05-27T09:58:44.984344 - Found comfy_kitchen backend cuda: {'available': False, 'disabled': True, 'unavailable_reason': 'Extension file not found: /Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/comfy_kitchen/backends/cuda/_C.abi3.so', 'capabilities': []}
2026-05-27T09:58:44.984373 - Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_mxfp8', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_mxfp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_mxfp8', 'scaled_mm_nvfp4']}
2026-05-27T09:58:44.990214 - Checkpoint files will always be loaded safely.
2026-05-27T09:58:45.006256 - Total VRAM 24576 MB, total RAM 24576 MB
2026-05-27T09:58:45.006330 - pytorch version: 2.12.0
2026-05-27T09:58:45.009356 - Mac Version (26, 5)
2026-05-27T09:58:45.009455 - Set vram state to: SHARED
2026-05-27T09:58:45.009488 - Device: mps
2026-05-27T09:58:45.092472 - Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
2026-05-27T09:58:46.670072 - Python version: 3.12.11 (main, Aug 18 2025, 19:02:39) [Clang 20.1.4 ]
2026-05-27T09:58:46.670158 - ComfyUI version: 0.22.2
2026-05-27T09:58:46.670382 - comfy-aimdo version: 0.3.0
2026-05-27T09:58:46.670603 - comfy-kitchen version: 0.2.8
2026-05-27T09:58:46.670935 - [Prompt Server] web root: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/web_custom_versions/desktop_app
2026-05-27T09:58:46.671529 - Asset seeder disabled
2026-05-27T09:58:46.671581 - [START] ComfyUI-Manager
2026-05-27T09:58:46.749026 - [ComfyUI-Manager] Using GitPython backend2026-05-27T09:58:46.749088 - 
2026-05-27T09:58:46.772790 - [ComfyUI-Manager] network_mode: public
2026-05-27T09:58:46.774758 - [ComfyUI-Manager] The matrix sharing feature has been disabled because the `matrix-nio` dependency is not installed.
	To use this feature, please run the following command:
	/Users/mpankau/ComfyUI/.venv/bin/python -m pip install matrix-nio

2026-05-27T09:58:47.442313 - 
Import times for custom nodes:
2026-05-27T09:58:47.442387 -    0.0 seconds: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/websocket_image_save.py
2026-05-27T09:58:47.442412 - 
2026-05-27T09:58:47.445887 - Context impl SQLiteImpl.
2026-05-27T09:58:47.445932 - Will assume non-transactional DDL.
2026-05-27T09:58:47.466704 - Starting server

2026-05-27T09:58:47.466921 - To see the GUI go to: http://127.0.0.1:8000
2026-05-27T10:00:31.945341 - FETCH ComfyRegistry Data [DONE]
2026-05-27T10:00:32.058209 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2026-05-27T10:00:32.063553 - FETCH DATA from: /Users/mpankau/ComfyUI/user/__manager/cache/1514988643_custom-node-list.json2026-05-27T10:00:32.063567 - 2026-05-27T10:00:32.068451 -  [DONE]2026-05-27T10:00:32.068475 - 
2026-05-27T10:00:32.078666 - [ComfyUI-Manager] All startup tasks have been completed.
2026-05-27T10:11:32.601655 - got prompt
2026-05-27T10:11:32.668903 - Using split attention in VAE
2026-05-27T10:11:32.670082 - Using split attention in VAE
2026-05-27T10:11:32.969415 - VAE load device: mps, offload device: cpu, dtype: torch.bfloat16
2026-05-27T10:11:33.026691 - Requested to load WanVAE
2026-05-27T10:11:33.121759 - loaded completely;  242.03 MB loaded, full load: True
2026-05-27T10:11:34.634939 - Interrupting prompt 68f9ce5a-97ac-4e4f-a700-1e75c00aedb5
2026-05-27T10:11:35.157366 - Processing interrupted
2026-05-27T10:11:35.160599 - Prompt executed in 2.55 seconds
2026-05-27T10:12:08.060371 - got prompt
2026-05-27T10:12:08.174296 - Found quantization metadata version 1
2026-05-27T10:12:08.174620 - Using MixedPrecisionOps for text encoder
2026-05-27T10:12:09.007780 - Requested to load QwenImageTEModel_
2026-05-27T10:12:09.028618 - loaded completely;  7910.28 MB loaded, full load: True
2026-05-27T10:12:09.032961 - CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
2026-05-27T10:12:31.344999 - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2026-05-27T10:12:31.350378 - model_type FLUX
2026-05-27T10:13:04.591148 - Requested to load QwenImage
2026-05-27T10:13:05.462851 - 0 models unloaded.
2026-05-27T10:17:05.592717 - loaded completely;  19483.95 MB loaded, full load: True
2026-05-27T10:17:05.978742 - 
  0%|          | 0/4 [00:00<?, ?it/s]2026-05-27T10:17:06.244193 - 
  0%|          | 0/4 [00:00<?, ?it/s]2026-05-27T10:17:06.244230 - 
2026-05-27T10:17:06.317006 - !!! Exception during processing !!! Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.
2026-05-27T10:17:06.348023 - Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 535, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 335, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 309, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 297, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 1578, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 1542, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/sample.py", line 74, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1180, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1070, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1052, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 995, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 981, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 751, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/k_diffusion/sampling.py", line 205, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 400, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 954, in __call__
    return self.outer_predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 961, in outer_predict_noise
    ).execute(x, timestep, model_options, seed)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 964, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 380, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 205, in calc_cond_batch
    return _calc_cond_batch_outer(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 213, in _calc_cond_batch_outer
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 325, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_base.py", line 182, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_base.py", line 226, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/qwen_image/model.py", line 427, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/qwen_image/model.py", line 499, in _forward
    hidden_states = self.img_in(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpankau/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 482, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 474, in forward_comfy_cast_weights
    weight, bias, offload_stream = cast_bias_weight(self, input, offloadable=True)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 352, in cast_bias_weight
    bias = bias.to(dtype=bias_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

2026-05-27T10:17:06.369313 - Prompt executed in 298.30 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Reply by vSnake87** [reply]
I prepared a more complete version of the patcher.

This version no longer depends on my local username or one fixed installation path. It searches for the relevant ComfyUI and comfy-kitchen files automatically, verifies that they contain the expected functions, creates backups, applies the patch only where needed, and runs a Python syntax check after patching.

It now covers the broader FP8/MPS fallback surface:
1. `comfy/float.py`
   - `stochastic_rounding()`
   - `stochastic_round_quantize_nvfp4()`
   - `stochastic_round_quantize_nvfp4_by_block()`

2. `comfy/quant_ops.py`
   - `_TensorCoreFP8LayoutBase.quantize()`

3. `comfy_kitchen/backends/eager/quantization.py`
   - `dequantize_per_tensor_fp8()`

This is still only a local workaround, not an official upstream fix, but it should be more useful for different Apple Silicon / macOS ComfyUI installations.

[patch_comfy_mps_fp8_full.py](https://github.com/user-attachments/files/28318600/patch_comfy_mps_fp8_full.py)

**Reply by androidpillai-ops** [reply]
> I tried this and it didn't work initially but I discovered the desktop app version had a little different directory for the quantization bit, after updating the script with the new path it worked great. Thank you for putting this together @vSnake87

Could you share the location please? I was trying to find it. The script (latest) runs, but fails to find the quantization bit

**Reply by ernest-cook** [reply]
> Could you share the location please? I was trying to find it. The script (latest) runs, but fails to find the quantization bit

```
FLOAT_PATH = Path("/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/float.py")
KITCHEN_PATH = Path("/Users/YOURHOMEDIRECTORYHERE/Documents/Comfyui/.venv/lib/python3.12/site-packages/comfy_kitchen/backends/eager/quantization.py")

```

I poked around in terminal and google until I found it but yours might be slightly different so definitely validate it before running

**Reply by deardaveed** [reply]
> I prepared a more complete version of the patcher.
> 
> This version no longer depends on my local username or one fixed installation path. It searches for the relevant ComfyUI and comfy-kitchen files automatically, verifies that they contain the expected functions, creates backups, applies the patch only where needed, and runs a Python syntax check after patching.
> 
> It now covers the broader FP8/MPS fallback surface:
> 
> 1. `comfy/float.py`
>    
>    * `stochastic_rounding()`
>    * `stochastic_round_quantize_nvfp4()`
>    * `stochastic_round_quantize_nvfp4_by_block()`
> 2. `comfy/quant_ops.py`
>    
>    * `_TensorCoreFP8LayoutBase.quantize()`
> 3. `comfy_kitchen/backends/eager/quantization.py`
>    
>    * `dequantize_per_tensor_fp8()`
> 
> This is still only a local workaround, not an official upstream fix, but it should be more useful for different Apple Silicon / macOS ComfyUI installations.
> 
> [patch_comfy_mps_fp8_full.py](https://github.com/user-attachments/files/28318600/patch_comfy_mps_fp8_full.py)

@vSnake87 
could you share which startup env vars or argument flags you're using for optimal performance + quality on your Apple Silicone? 

i'm using '--force-fp16 --fp32-vae --use-pytorch-cross-attention --highvram' with 'PYTORCH_MPS_HIGH_WATERMARK_RATIO' set to 0.0 for my M1 Max 64GB. but not sure because i get different info from everywhere i've been searching
