### DISCUSSION TITLE
COMFYUI ERRORS

### DISCUSSION THREAD

**Discussion by Blahblahdenver** [Comfy-Org/ComfyUI#4194] [General]
I've been working through errors for weeks, updating and adjusting everything I can and using every resource out there. it's been overwhelming so I'm starting a thread here. ill post the remaining errors I've been encountering and if anyone can help out I would greatly appreciate it.

2024-08-03 22:15:05.853 [Debug] [ComfyUI-0/STDOUT] Warn!: C:\SwarmUI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
2024-08-03 22:15:05.853 [Debug] [ComfyUI-0/STDOUT] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].

2024-08-03 22:15:01.574 [Verbose] Comfy backend 0 failed to load value set, but ignoring error: HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:7821)

this isnt an error but ive got two RTX, a 2070 and 2060. both have 7.5 compute but comfy only uses one.
2024-08-03 22:15:01.633 [Debug] [ComfyUI-0/STDERR] Device: cuda:0 NVIDIA GeForce RTX 2070 : cudaMallocAsync

2024-08-03 22:15:06.664 [Verbose] Comfy backend 0 failed to load value set, but ignoring error: HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:7821)

2024-08-03 22:15:15.593 [Debug] [ComfyUI-0/STDOUT] [33m[rgthree] Note: [0mIf execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.[00m

I've installed accelerate over and over. it's saved on the pc and in the path but the logs keep showing this error.
2024-08-03 22:16:11.087 [Debug] [ComfyUI-0/STDERR] Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: 

I've installed 3 versions of Cuda and tried them all.
2024-08-03 22:16:20.683 [Debug] [ComfyUI-0/STDOUT] Warn!: C:\SwarmUI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)

I've tried every combination you can think of 
2024-08-03 22:16:20.826 [Debug] [ComfyUI-0/STDOUT] Warn!: C:\SwarmUI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\diffusers\models\attention_processor.py:1584: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)

once again this one.
2024-08-03 22:16:51.354 [Debug] [ComfyUI-0/STDOUT] Warn!: C:\SwarmUI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
2024-08-03 22:16:51.354 [Debug] [ComfyUI-0/STDOUT] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].

I'm using SwarmUI with ComfyUI backend. I update all often. my main use is creating 3d images with Comfy3DPack.
this feed comes from generating with the one of the example workflows. 
also Preview3DMesh does NOT work. I've read forums and see many other people have the same issue but the only one people offer ideas for are where someone is accessing ComfyUI remotely. it does not work locally.

Please dear  Gosh someone help me.

**Comment by rastalord** [comment]
Regularly have the same error. Only thing that works for me is constantly jumping between dev build and release. They're constsntly updating it so it's probably a persistent bug in architecture of the swarm - didn't have these problems with bare Comfy
