### ISSUE TITLE
Custom-node installation done but still missing

### ISSUE THREAD

**Issue by frank4133** [Comfy-Org/ComfyUI#11762]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

Actually, this is not my primary issue.

My original problem arose today after updating ComfyUI to the latest version. I encountered the error: "CUDA error: no kernel image is available for execution on the device." This was unexpected, as I was using an identical workflow that had previously worked without issues.

I did check out #10468 but it didn't solve my problem because I am using an RTX 5090. Then, I attempted to upgrade PyTorch. The installed version was 2.9+cuda126 (though I recall initially installing CUDA 12.8 because when 50 series just came out, there was also this kind of bugs, and the solution was to install Torch with cuda128). 

Unfortunately, the environment became unstable during my troubleshooting attempts, so I decided to perform a clean reinstallation. Initially, I manually copied my old custom nodes to the new ComfyUI folders; while the ComfyUI Launch Menu flagged errors, the individual status checks appeared normal and no error reported in the terminal. I then decided to reinstall ComfyUI a second time, installing nodes strictly via the Custom Nodes Manager. However, the system continues to report missing nodes, even though the Manager indicates they are successfully installed. On a positive note, my GPU is now functioning correctly (installed version now is 2.9.1+cu130). Since the console logs show no explicit error messages, only the missing node alerts, I am unsure what specific diagnostic information I should provide to help resolve this.

### Logs

```powershell

```

**Comment by changpd25-cell** [comment]
The quality of comfyui is getting worse and worse. Most updates cause new problems and even cause the entire tool to crash. This damn tool is no longer recommended for others to use. It's just a game for the developers to entertain themselves.

**Comment by Kosinkadink** [comment]
Could you post your full start up log from the terminal? As well as a screenshot of the lost of nodes the frontend reports as missing when you load a workflow?

Even if a node pack is installed, if it runs into errors when booting up, that is currently not reported in the frontend so it will only appear as the nodes "missing" in the graph. The console logs will show that a node pack failed to load, and further up it has the exact exception info.

**Comment by frank4133** [comment]
I should amend my original statement, "the system continues to report missing nodes, even though the Manager indicates they are successfully installed.", it should actually be, I press Install and the progression bar shows installation completed, but in Manger menu, I still can press Install, and nothing happens. And from the log, it seems the git clone failed because of the imported package's name?! But I don't know how it would happen. I mean, this kind of installation failure happens from time to time, and mostly it can be solved by restarting ComfyUI and installing nodes again. But this latest version, it can never be solved.

Below is the screenshot of the missing nodes and the terminal log after I click Install All,

<img width="238" height="215" alt="Image" src="https://github.com/user-attachments/assets/1d9588a0-d6ee-4ff8-859e-dcfdfefd6a55" />


<details>
<summary>Click to expand full log</summary>

```
Adding extra search path custom_nodes C:\Users\frank\ComfyUI\custom_nodes
Adding extra search path download_model_base D:\comfy\models
Adding extra search path checkpoints D:\comfy\models\checkpoints
Adding extra search path vae D:\comfy\models\vae
Adding extra search path loras D:\comfy\models\loras
Adding extra search path unet D:\comfy\models\unet
Adding extra search path diffusion_models D:\comfy\models\diffusion_models
Adding extra search path diffusion_models D:\comfy\models\unet
Adding extra search path diffusers D:\comfy\models\diffusers
Adding extra search path controlnet D:\comfy\models\controlnet
Adding extra search path clip D:\comfy\models\clip
Adding extra search path clip_vision D:\comfy\models\clip_vision
Adding extra search path style_models D:\comfy\models\style_models
Adding extra search path gligen D:\comfy\models\gligen
Adding extra search path upscale_models D:\comfy\models\upscale_models
Adding extra search path facerestore_models D:\comfy\models\facerestore_models
Adding extra search path embeddings D:\comfy\models\embeddings
Adding extra search path hypernetworks D:\comfy\models\hypernetworks
Adding extra search path photomaker D:\comfy\models\photomaker
Adding extra search path insightface D:\comfy\models\insightface
Adding extra search path ultralytics D:\comfy\models\ultralytics
Adding extra search path sams D:\comfy\models\sams
Adding extra search path onnx D:\comfy\models\onnx
Adding extra search path vae_approx D:\comfy\models\vae_approx
Adding extra search path configs D:\comfy\models\configs
Adding extra search path text_encoders D:\comfy\models\text_encoders
Adding extra search path classifiers D:\comfy\models\classifiers
Adding extra search path custom_nodes C:\Users\frank\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes
Setting output directory to: C:\Users\frank\ComfyUI\output
Setting input directory to: C:\Users\frank\ComfyUI\input
Setting user directory to: C:\Users\frank\ComfyUI\user
[START] Security scan
[DONE] Security scan
** ComfyUI startup time: 2026-01-10 15:55:12.875
** Platform: Windows
** Python version: 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]
** Python executable: C:\Users\frank\ComfyUI\.venv\Scripts\python.exe
** ComfyUI Path: C:\Users\frank\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
** ComfyUI Base Folder Path: C:\Users\frank\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
** User directory: C:\Users\frank\ComfyUI\user
** ComfyUI-Manager config path: C:\Users\frank\ComfyUI\user\__manager\config.ini
** Log path: C:\Users\frank\ComfyUI\user\comfyui.log
[ComfyUI-Manager] Skipped fixing the 'comfyui-frontend-package' dependency because the ComfyUI is outdated.
[PRE] ComfyUI-Manager
Checkpoint files will always be loaded safely.
Total VRAM 32607 MB, total RAM 63124 MB
pytorch version: 2.9.1+cu130
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync
Using async weight offloading with 2 streams
Enabled pinned memory 28405.0
working around nvidia conv3d memory bug.
Found comfy_kitchen backend triton: {'available': False, 'disabled': True, 'unavailable_reason': "ImportError: No module named 'triton'", 'capabilities': []}
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend cuda: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Using pytorch attention
Python version: 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]
ComfyUI version: 0.8.2
[Prompt Server] web root: C:\Users\frank\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
[START] ComfyUI-Manager
[ComfyUI-Manager] network_mode: public
[ComfyUI-Manager] The matrix sharing feature has been disabled because the `matrix-nio` dependency is not installed.
        To use this feature, please run the following command:
        C:\Users\frank\ComfyUI\.venv\Scripts\python.exe -m pip install matrix-nio

Total VRAM 32607 MB, total RAM 63124 MB
pytorch version: 2.9.1+cu130
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync
Using async weight offloading with 2 streams
Enabled pinned memory 28405.0
Adding C:\Users\frank\ComfyUI\custom_nodes to sys.path
Adding C:\Users\frank\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\frank\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
C:\Users\frank\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Loaded comfyui_controlnet_aux nodes from C:\Users\frank\ComfyUI\custom_nodes\comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Could not find IPAdapter nodes
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V8.28.2)
### Loading: ComfyUI-Impact-Pack (V8.28.2)
Loaded ImpactPack nodes from C:\Users\frank\ComfyUI\custom_nodes\comfyui-impact-pack
[Impact Pack] Wildcard total size (0.00 MB) is within cache limit (50.00 MB). Using full cache mode.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcard total size (0.00 MB) is within cache limit (50.00 MB). Using full cache mode.
[Impact Pack] Wildcards loading done.
[ComfyUI-Easy-Use] server: v1.3.4 Loaded
[ComfyUI-Easy-Use] web root: C:\Users\frank\ComfyUI\custom_nodes\comfyui-easy-use\web_version/v2 Loaded
ComfyUI-GGUF: Allowing full torch compile
### Loading: ComfyUI-Impact-Pack (V8.28.2)
[Impact Pack] Wildcard total size (0.00 MB) is within cache limit (50.00 MB). Using full cache mode.
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Subpack (V1.3.5)
[Impact Pack/Subpack] Using folder_paths to determine whitelist path: C:\Users\frank\ComfyUI\user\default\ComfyUI-Impact-Subpack\model-whitelist.txt
[Impact Pack/Subpack] Ensured whitelist directory exists: C:\Users\frank\ComfyUI\user\default\ComfyUI-Impact-Subpack
[Impact Pack/Subpack] Loaded 0 model(s) from whitelist: C:\Users\frank\ComfyUI\user\default\ComfyUI-Impact-Subpack\model-whitelist.txt
[Impact Subpack] ultralytics_bbox: C:\Users\frank\ComfyUI\models\ultralytics\bbox
[Impact Subpack] ultralytics_segm: C:\Users\frank\ComfyUI\models\ultralytics\segm
[Impact Subpack] ultralytics_bbox: C:\Users\frank\ComfyUI\models\ultralytics\bbox, D:\comfy\models\ultralytics\bbox
[Impact Subpack] ultralytics_segm: C:\Users\frank\ComfyUI\models\ultralytics\segm, D:\comfy\models\ultralytics\segm
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
[C:\Users\frank\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\frank\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[C:\Users\frank\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False
[C:\Users\frank\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']

[rgthree-comfy] Loaded 48 epic nodes. 🎉

[rgthree-comfy] ComfyUI's new Node 2.0 rendering may be incompatible with some rgthree-comfy nodes and features, breaking some rendering as well as losing the ability to access a node's properties (a vital part of many nodes). It also appears to run MUCH more slowly spiking CPU usage and causing jankiness and unresponsiveness, especially with large workflows. Personally I am not planning to use the new Nodes 2.0 and, unfortunately, am not able to invest the time to investigate and overhaul rgthree-comfy where needed. If you have issues when Nodes 2.0 is enabled, I'd urge you to switch it off as well and join me in hoping ComfyUI is not planning to deprecate the existing, stable canvas rendering all together.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Users\frank\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 220 nodes successfully.

        "The best revenge is massive success." - Frank Sinatra

Blocked by policy: C:\Users\frank\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager

Import times for custom nodes:
   0.0 seconds: C:\Users\frank\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-mxtoolkit
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui_essentials
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-wd14-tagger
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui_ultimatesdupscale
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-impact-pack
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-custom-scripts
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-kjnodes
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-frame-interpolation
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-florence2
   0.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-impact-subpack
   0.4 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui_smznodes
   0.5 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-videohelpersuite
   1.0 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-art-venture
   1.5 seconds: C:\Users\frank\ComfyUI\custom_nodes\was-node-suite-comfyui
   3.4 seconds: C:\Users\frank\ComfyUI\custom_nodes\comfyui-easy-use

Failed to initialize database. Please ensure you have installed the latest requirements. If the error persists, please report this as in future the database will be required: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Starting server

To see the GUI go to: http://127.0.0.1:8000
comfyui-frontend-package not found in requirements.txt
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/clipspace.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/widgetInputs.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/button.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: C:\Users\frank\ComfyUI\user\__manager\cache\1514988643_custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
[ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.
FETCH DATA from: C:\Users\frank\ComfyUI\.venv\Lib\site-packages\comfyui_manager\custom-node-list.json [DONE]
Download: git clone 'https://github.com/giriss/comfy-image-saver'
[!] Traceback (most recent call last):
[!]   File "C:\Users\frank\ComfyUI\.venv\Lib\site-packages\comfyui_manager\common\git_helper.py", line 12, in <module>
[!]     from comfyui_manager.common.timestamp_utils import get_backup_branch_name
[!]   File "C:\Users\frank\ComfyUI\.venv\Lib\site-packages\comfyui_manager\__init__.py", line 6, in <module>
[!]     from comfy.cli_args import args
[!] ModuleNotFoundError: No module named 'comfy'
[ComfyUI-Manager] Installation failed:
Failed to clone repo: https://github.com/giriss/comfy-image-saver
FETCH DATA from: C:\Users\frank\ComfyUI\.venv\Lib\site-packages\comfyui_manager\custom-node-list.json [DONE]
Download: git clone 'https://github.com/ramyma/A8R8_ComfyUI_nodes'
[!] Traceback (most recent call last):
[!]   File "C:\Users\frank\ComfyUI\.venv\Lib\site-packages\comfyui_manager\common\git_helper.py", line 12, in <module>
[!]     from comfyui_manager.common.timestamp_utils import get_backup_branch_name
[!]   File "C:\Users\frank\ComfyUI\.venv\Lib\site-packages\comfyui_manager\__init__.py", line 6, in <module>
[!]     from comfy.cli_args import args
[!] ModuleNotFoundError: No module named 'comfy'
[ComfyUI-Manager] Installation failed:
Failed to clone repo: https://github.com/ramyma/A8R8_ComfyUI_nodes

After restarting ComfyUI, please refresh the browser.
</details>

**Comment by dish72** [comment]
I just started having this exact same issue following the upgrade to ComfyUI Desktop 0.7.2 installation from 0.7.0.

I erroneously then made the assumption that the upgrade to ComfyUI Desktop 0.7.2 corrupted something with my installation and backed up my models and completely uninstalled, wiped remanences, and re-installed ComfyUI Desktop 0,7.2 from scratch only to have the exact same issue with a clean ComfyUI Desktop 0.7.2 installation with no custom nodes yet installed.

Along with the error reported by the OP, custom node installation via the ComfyUI Manager also fail.

All node installations seem to give the "ModuleNotFoundError: No module named 'comfy'" error in the logs, although loading a workflow with missing nodes installed seems to give a successful installation of these missing nodes, even though it had actually failed.

**Comment by sb10** [comment]
I also hit this same issue. I uninstalled the desktop app, reinstalled 0.7.2 from scratch, migrated only workflows and models, started it up, opened a previously working workflow, was prompted that there were missing nodes and used the option to install them all with the manager, did the prompted restart, and that seemed to work (no more red highlighted nodes).
However, the missing nodes feature did not detect that I was using RES4LYF. So I used the manager to install that. 

It blindly prompts "to apply changes, please restart ComfyUI", despite the error in the logs:

```
Download: git clone 'https://github.com/ClownsharkBatwing/RES4LYF'
[!] Traceback (most recent call last):
[!]   File "D:\ComfyUI_desktop\.venv\Lib\site-packages\comfyui_manager\common\git_helper.py", line 12, in <module>
[!]     from comfyui_manager.common.timestamp_utils import get_backup_branch_name
[!]   File "D:\ComfyUI_desktop\.venv\Lib\site-packages\comfyui_manager\__init__.py", line 6, in <module>
[!]     from comfy.cli_args import args
[!] ModuleNotFoundError: No module named 'comfy'
[ComfyUI-Manager] Installation failed:
Failed to clone repo: https://github.com/ClownsharkBatwing/RES4LYF
```

So the manager was able to install some but not all custom nodes. If I manually clone the repo to the custom nodes folder and use the venv to install its requirements, this breaks the desktop app completely, making it think the python environment is missing, but it is unable to reinstall.

By comparison, the windows portable version fresh install of latest version was able to install all the missing nodes for the same workflow, then was able to install RES4LYF after searching for it, and it worked without issue.

**Comment by frank4133** [comment]
> So the manager was able to install some but not all custom nodes. If I manually clone the repo to the custom nodes folder and use the venv to install its requirements, this breaks the desktop app completely, making it think the python environment is missing, but it is unable to reinstall.

That also happened to me while I was trying to solve the dependency problems... I manually modified the venv env and the software just detected the whole env was gone...

**Comment by lustfeind** [comment]
Unfortunately I've to report this strange issue: 

- When comfyui detects missing nodes, it seems to install them well, but after restart they are missing again. 
- In the manager they don't show as "missing" anymore, in fact the manager thinks that they are installed fine
- Endless loop,.. the never get installed.

Strange thing,.. I'm pretty sure that this is a issue with the new ComfyUI version, because this happens with older nodes who installed well in a older version of ComfyUI.

I'm with the Mac Desktop version.
