### ISSUE TITLE
TextEncoder VRAM not released before KSampler → OOM on low-VRAM GPUs (proposed fix: free vbar cached tensors)

### ISSUE THREAD

**Issue by isxzkas-tech** [Comfy-Org/ComfyUI#12335]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

Summary
On low-VRAM GPUs, recent stable releases can OOM reliably because TextEncoder GPU-resident cached tensors (vbar cache) are not released before entering KSampler. This appears to be a regression compared to v0.10 behavior. A small, targeted fix can free only the cached tensor data while keeping the structure intact, allowing on-demand reload later.

Impact

Low-VRAM systems frequently OOM even on workflows that previously ran.

This blocks practical use for a large portion of the user base.

Likely affects setups with many custom nodes because memory headroom is smaller and caching behavior matters more.

Observed behavior

Before KSampler begins, TextEncoder’s GPU-resident cache remains allocated.

VRAM is not sufficiently freed, causing OOM at/near KSampler start.

Expected behavior

Prior to KSampler execution, TextEncoder cached tensor data should be evicted/partially unloaded (without fully detaching or destroying model structure), so VRAM is available.

Root cause (as analyzed / compared to v0.10)
In comfy/model_management.py (free_memory() near ~L630), the “dynamic” handling path assumes dynamic models do not need unloading and effectively results in no VRAM being freed (memory_to_free = 0). In practice, TextEncoder’s vbar cache can keep real tensor data on GPU and must be evicted to avoid OOM.

Proposed fix (minimal behavioral change)
Instead of “do nothing” in the dynamic path, keep the model structure but explicitly free TextEncoder vbar cached tensor data:

Before: memory_to_free = 0 → TextEncoder VRAM remains

After: call vbar.free_memory() (or equivalent partial unload) → cached tensor data freed; structure preserved

Effect: VRAM is available before KSampler; TextEncoder reloads data on-demand via vbar when used again; no functional changes expected.

Additional fixes included in patch

comfy/model_patcher.py (~L1486): In ModelPatcherDynamic.load(), skip module iteration/setup when patches_uuid has not changed (avoids redundant initialization).

comfy/model_patcher.py (~L832): lowvram_patch_counter should be reassigned (=) not accumulated (+=) because load() recreates patches each time.

Patch

Patch file: vram_management_fix.patch

Targets: comfy/model_patcher.py, comfy/model_management.py

Request

Please treat this as a regression affecting low-VRAM users and consider fast-tracking the minimal fix above.

Additionally, consider adding a low-VRAM regression test scenario around TextEncoder → free_memory → KSampler to prevent recurrence.

[vram_management_fix.patch](https://github.com/user-attachments/files/25140008/vram_management_fix.patch)

### Logs

```powershell

```

**Comment by tilkinsc** [comment]
I am having a recent issue with qwen-image Q4/Q5 quants because of this on a `RTX 4070ti super 16gb` card. The error happens on the ksampler step, which I found very odd initially because thats the actual sampling why would we need to alloc more? I am using SDXL resolutions which are roughly 20-40% smaller than qwen resolutions. I used to be able to chain generate images with the same exact node paths, but now I am lucky if my system barely has enough vram with zero programs open. I can't make xorg and and DE take any less vram than they are (347mb, 59mb, respectively). So I am stuck right now with the latest of latest commits potentially putting up a fight with me, since I like bleeding edge. The issue goes away when not using LORAs (I can't use the 4/8 step lightning LORA 👎 ). I use RGTHREE to load the LORAs typically because it seems to load better than the comfy provided one, which ooms me regardless as I think it loads the model into vram first or something.

**Comment by an80sPWNstar** [comment]
I'm still having this same issue using the multigpu nodes. It is driving me nuts.

**Comment by ryamldess** [comment]
I've noticed that this issue seems to be resolved by either explicitly enabling CUDA Malloc or disabling smart memory in Server-Config or via CLI flags if running from VS. HTH until there is an official patch/fix. Idk if that will apply to everyone, but it seems to the case on my system anyway. @isxzkas-tech I noticed the same issue in model_management.py, which seems to be by design based on the comment:

`#don't actually unload dynamic models for the sake of other dynamic models
#as that works on-demand.`

But that means that VRAM is only then freed once you close the app. On my system with an RTX 3090 and 24 GB of VRAM, it isn't causing OOM's, and if I run a KSampler over and over it just stays pegged at about 9GB, so it isn't a big issue for me atm, but I can how, if you have less VRAM and/or are running a lot of different models, it could.

**Comment by sqweek** [comment]
I'm seeing similar behaviour where memory allocated by ComfyUI 0.16.0 on Windows for model loading never seems to be returned to the system. I'm trying to run a txt2vid workflow which I have successfully run in the past under Linux on a different machine with similar memory characteristics:

Working environment: ComfyUI 0.3.66 (c170fd2db598a0bdce56f80e22e83e10ad731421), Linux, NVIDIA RTX 3080Ti Laptop GPU 16G VRAM, 32G system RAM
Failing environment: ComfyUI 0.16.0 (e04d0dbe), Windows, NVIDIA RTX 5070Ti GPU 16G VRAM, 32G system RAM

The workflow is a typical WAN workflow with two KSamplers, first using the "high noise" model followed by the "low noise" model. During the first KSampler step, GPU VRAM usage is up around 15.5/16.0 GB, so unloading the high noise model is going to be crucial to fit the low noise model into VRAM.

### Failure mode 1: python crash

Initially python was straight up crashing when attempting to load the low noise model. I believe this was because CUDA tried to fallback to "shared GPU memory" to satisfy an allocation but system memory was also maxed out.

Adding `--gpu-only` to ComfyUI args resolved this crash, my hypothesis is that it reduced system memory usage which enabled CUDA's memory fallback to succeed. This leads to...

### Failure mode 2: slooooow KSampler and VAEDecode error

Obviously when CUDA starts using "shared GPU memory" instead of VRAM performance drops dramatically -- the second KSampler does work but takes 80x longer than the first. However a subsequent step failed in a CUDA call because it was asked to operate on different pieces of data one of which was in VRAM and one of which was in system RAM (ie. shared GPU memory).

Eventually I found [this guide](https://discuss.pytorch.org/t/documented-fix-slow-execution-pytorch-using-gpu-shared-memory/218909) which explained how to disable CUDA's fallback-to-system-memory behaviour. This leads to...

### Failure mode 3: torch.OutOfMemoryError

With CUDA restricted to using VRAM only the whole system behaves much better, now Comfy reports a proper OutOfMemoryError when VRAM is exhausted instead of the python process crashing unceremoniously :)

I've added a bunch of "[Unload Model](https://github.com/SeanScripts/ComfyUI-Unload-Model)" nodes into the workflow in an attempt to forcefully eject the high-noise model from VRAM after the first KSampler, however monitoring VRAM usage via Task Manager does not show any appreciable drop.

In fact, even after the OOM error:

```
torch.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 15.06 GiB
Requested               : 25.00 MiB
Device limit            : 15.92 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

...

Got an OOM, unloading all loaded models.
```

where Comfy claims to unload all loaded models, GPU VRAM usage from the system perspective (Task Manager + nvidia-smi) is still 15.5/16.0 GB and if I rerun the workflow immediately it gets nowhere; I have to restart ComfyUI for VRAM usage to actually drop.

.... hmm, while I was typing this GPU VRAM usage _has_ dropped down to 0.8/16.0 GB so there may also be some kind of timeout mechanism in play? I'll re-run this with a timer and see if I can pin down how long that takes. ... 15 minutes later the VRAM usage hasn't dropped, so I'm not sure what triggered this.

Another interesting observation in Task Manager: if I go to the process details view and add "Dedicated GPU Memory" to the visible columns, the VRAM attributed to `python.exe` is _very_ low after the OOM, only 396KB. In fact the total of the column in this view is only ~750MB (mostly attributed to `dwm.exe`), so there's a huge discrepancy here and it's not obvious from the figures where the rest of the VRAM is tied up. It's definitely attached to `python.exe` somehow (maybe in its ~48GB of "Commit Size"), because if I ctrl-C the comfy server VRAM usage immediately drops back down to 0.8/16.0GB.

Having experimented with many command-line args, I'm currently running with `--disable-xformers --gpu-only --force-fp16 --use-sage-attention --cuda-malloc --disable-pinned-memory --disable-dynamic-vram`

If I throw `--disable-mmap` into the mix, then the process details view does show ~15GB of "Dedicated GPU Memory" attributed to `python.exe` after the OOM (directly after the OOM it briefly drops to 0 before jumping back up to 15GB).

**Comment by sqweek** [comment]
I experimented with isxzkas-tech's patch from the initial comment (and removing the `--disable-dynamic-vram` flag since in 0.16.0 the relevant logic is gated behind `if not DISABLE_SMART_MEMORY`), but it doesn't resolve the problem for me.

Adding some logging to `model_patcher.ModelPatcher.unpatch_model()` and `model_management.free_memory()` confirms that comfy is at least trying to unload models at appropriate times. I see these during workflow execution:

```
...
Unpatching WanTEModel with loaded_size=6731314268
...
100%|███████████████████████████████████| 3/3 [00:03<00:00,  1.32s/it]
Unload Model:
 - Model found in memory, unloading...
0: WAN21 keep_loaded: False  is_dead: False  loaded_size: 14294421834
Unpatching WAN21 with loaded_size=14294421834
...
```

ie. unpatch_model() is automatically called on the text encoder model (WanTEModel) at some point after it has done its job. WAN21 is being unpatched here by the "Unload Model" node that I explicitly added, however I suspect it would get unpatched regardless as the problem here doesn't seem to be with comfy's intent (evidence suggests that its model loading/unloading logic is sound), but rather an issue communicating with the CUDA layer to actually reclaim VRAM.

**Comment by sqweek** [comment]
> but rather an issue communicating with the CUDA layer to actually reclaim VRAM.

More specifically, communicating with pytorch which is ultimately responsible for allocating the GPU VRAM. Because pytorch uses a caching allocator, VRAM that has been "freed" by the application may still be held by pytorch for future use, so it's not necessarily a problem that VRAM is still allocated from the system perspective.

However the fact that pytorch throws an OutOfMemoryError here when Comfy's model_management code thinks that no models are loaded is a pretty strong indication that Comfy is somehow holding on to a reference of the underlying Buffers/Tensors and preventing pytorch from reusing the associated VRAM...

**Comment by ryamldess** [comment]
@sqweek Idk the full details, but looking at the code, it doesn't seem like it is 100% down to pytorch, although I could be wrong about that. It seems like there is an issue with the conditional logic for memory management in general. There are several flags, like the ones you mentioned, for managing VRAM in some capacity, but there is not a common, sane code flow that manages state for that. My hypothesis is that there is a logical flaw in this partially spaghettified portion of the codebase--it happens, especially in open source--that just needs some special attention and debugging to refactor to something potentially more centralized, perhaps an entire new class to which high-level VRAM memory management is delegated. Not real memory management--just at the high level. This is a hunch based on looking the code for maybe 10 minutes--I just noticed a lot of code smells with conditional logic. Not entirely surprising given that a lot of it is generated code. I could be wrong, but with 22 years of experience, you kind of get a spidey sense just scanning certain code. So take it with many grains of salt.

The thing is, there are a lot of frameworks and dependencies in Comfy that have handles to VRAM under the hood--and I think when you have a complex graph of nodes, some of them are 'stepping on' other nodes; and that's getting it into a horked state with the scheduler in CUDA and/or Windows. It's also possible this could be rectified another way, by, for instance, adding a brief delay between node execution--it's possible that certain things are being called synchronously that should by async.

I would look into it further, but unfortunately my attention is drawn elsewhere. I know this is mercenary of me, but my main interest in this was in gaining employment with Comfy Org--and since I am no longer a candidate, I have to address my attention to other things to survive the techbropocalypse that is occurring. No shade or anything, I just didn't get the job. The role was for the desktop engineer, so if I had gotten the role, I would probably be heads down on this rn. I have a lot of experience with exactly these kinds of OOM issues in client software as a gameplay systems engineer. Good news is, they passed on me, so that means they are probably hiring someone else even more badass ;), and I imagine this has to be one of their top priorities. They mentioned performance a lot in the hiring process and the JD, so I feel like this has to be at the top of the stack somewhere. For me, personally, it looks like issue no. 1, but not having digged deeper into the code or the issues tab, perhaps I am mistaken.

**Comment by sqweek** [comment]
My case seems to be somehow linked to this old workflow, which also exhibited other problems when loaded into current versions of ComfyUI (eg. the workflow includes GGUF model loader nodes which I am not using, but if I delete those nodes Comfy hits an error trying to dereference a None value when running the workflow).

I recreated a similar workflow from scratch, and this one is working fine and performing well. Task Manager now shows VRAM usage going up and down as needed while running the workflow. I'm also no longer using `--gpu-only` which has greatly reduced VRAM usage overall, maybe related. In conclusion Comfy 0.16.0 is in fact capable of managing VRAM well, but apparently old workflows can behave unpredictably (or maybe there was some weird custom node in the mix that is not present in my reimplementation).
