### ISSUE TITLE
this came out after i ran "python main.py"

### ISSUE THREAD

**Issue by ilxy2** [Comfy-Org/ComfyUI#12588]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

plz help

### Logs

```powershell
D:\ComfyUi\ComfyUI>python main.py
C:\Program Files\python\Lib\site-packages\torch\cuda\__init__.py:184: UserWarning: cudaGetDeviceCount() returned cudaErrorNotSupported, likely using older driver or on CPU machine (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10\cuda\CUDAFunctions.cpp:88.)
  return torch._C._cuda_getDeviceCount() > 0
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend cuda: {'available': False, 'disabled': False, 'unavailable_reason': 'CUDA not available on this system', 'capabilities': []}
Found comfy_kitchen backend triton: {'available': False, 'disabled': True, 'unavailable_reason': "ImportError: No module named 'triton'", 'capabilities': []}
Checkpoint files will always be loaded safely.
```

**Comment by GlamoramaAttack** [comment]
If you chose a manual installation:

D:\ComfyUI\venv\Scripts>

D:\ComfyUI\venv\Scripts>activate

(venv) D:\ComfyUI\venv\Scripts>

(venv) D:\ComfyUI>

(venv) D:\ComfyUI>python main.py

Python should be in the PATH of your system. To make the start easier, write a start script/batch file in notepad and change .txt to .bat after saving.

> call D:\ComfyUI\venv\Scripts\activate.bat
>  
> python main.py 
> 
> pause

You'll probably get more error messages because of:

> 
UserWarning: cudaGetDeviceCount() returned cudaErrorNotSupported, likely using older driver or on CPU machine

**Comment by ilxy2** [comment]
thank for ur reply,i solved it,i found it turned out my Nvidia Game Ready Driver is too old to match my pytorch and cuda
